'use client';
import { useState } from 'react';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { firebaseConfigured, getFirebase } from '@/lib/firebase';
import SiteChrome from '@/app/components/SiteChrome';
export default function NoteSearchPage(){
 const [term,setTerm]=useState(''),[results,setResults]=useState<any[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const search=async()=>{setLoading(true);setMessage('');setResults([]);if(!firebaseConfigured()){setMessage('Public note search needs Firebase to be configured.');setLoading(false);return}try{const {db}=getFirebase();const snap=await getDocs(query(collection(db,'notes'),where('public','==',true)));const t=term.trim().toLowerCase();const found=snap.docs.map(d=>({id:d.id,...d.data()})).filter((n:any)=>!t||String(n.title||'').toLowerCase().includes(t)).slice(0,30);setResults(found);if(!found.length)setMessage('no public notes found for that title.')}catch{setMessage('could not load public notes right now.')}setLoading(false)};
 return <SiteChrome><main className="search-page"><section className="search-card"><p className="kicker">shared study desk</p><h1>find notes</h1><p className="sub">search public student notes by title.</p><div className="searchbar"><input value={term} onChange={e=>setTerm(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="e.g. data structures"/><button onClick={search}>{loading?'searching…':'search'}</button></div><div className="results">{results.map((note:any)=><article key={note.id}><h2>{note.title}</h2><p>{String(note.body||'').slice(0,220)}{String(note.body||'').length>220?'…':''}</p><small>{note.authorName||'Stuko student'}</small></article>)}</div>{message&&<p className="message">{message}</p>}</section></main><style jsx>{`.search-page{min-height:calc(100svh - 150px);padding:150px 20px 100px;display:grid;place-items:center}.search-card{width:min(900px,100%);padding:42px;border:1px solid var(--glass-border);border-radius:30px;background:var(--glass-bg);backdrop-filter:blur(12px);color:var(--page-text)}.kicker{font:12px monospace;letter-spacing:.15em;text-transform:uppercase}.search-card h1{font-size:clamp(48px,7vw,80px);font-weight:400;letter-spacing:-.07em;margin:10px 0}.sub{opacity:.65}.searchbar{display:flex;gap:10px;margin-top:30px}.searchbar input{flex:1;min-width:0;border:1px solid var(--glass-border);border-radius:999px;background:transparent;color:inherit;padding:14px 18px;font:inherit}.searchbar button{border:0;border-radius:999px;padding:14px 22px;background:var(--page-text);color:var(--page-bg);cursor:pointer}.results{display:grid;gap:12px;margin-top:28px}.results article{padding:20px;border:1px solid var(--glass-border);border-radius:20px;background:rgba(255,255,255,.05)}.results h2{margin:0 0 8px;font-size:21px}.results p{margin:0 0 12px;opacity:.72;line-height:1.6}.results small{opacity:.5}.message{opacity:.6;margin-top:22px}@media(max-width:600px){.searchbar{flex-direction:column}}`}</style></SiteChrome>
}