'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { collection, getDocs } from 'firebase/firestore';
import { firebaseConfigured, getFirebase } from '@/lib/firebase';
import SiteChrome from '@/app/components/SiteChrome';

type Note={id:string;title:string;body:string;authorName?:string;public?:boolean};

export default function NoteSearchPage(){
 const [term,setTerm]=useState(''),[results,setResults]=useState<Note[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[searched,setSearched]=useState(false);
 const localPublic=()=>{try{const notes=JSON.parse(localStorage.getItem('stuko-saved-notes')||'[]');return Array.isArray(notes)?notes.filter((n:any)=>n.public).map((n:any)=>({id:String(n.id),title:String(n.title||'Untitled'),body:String(n.body||''),authorName:'You',public:true})):[]}catch{return[]}};
 const load=async(q:string)=>{setLoading(true);setMessage('');setSearched(true);try{let all:Note[]=[];if(firebaseConfigured()){try{const {db}=getFirebase();const snap=await getDocs(collection(db,'notes'));all=snap.docs.map(d=>({id:d.id,...d.data()} as Note)).filter(n=>n.public===true);}catch{all=[];}}
 const local=localPublic();const merged=[...all,...local.filter(l=>!all.some(n=>n.title.toLowerCase()===l.title.toLowerCase()))];const t=q.trim().toLowerCase();const found=merged.filter(n=>!t||n.title.toLowerCase().includes(t)).slice(0,50);setResults(found);if(!found.length)setMessage(t?'no public notes found for that title.':'no public notes available yet.');}catch{setResults([]);setMessage('search is temporarily unavailable.');}finally{setLoading(false)}};
 useEffect(()=>{load('')},[]);
 return <SiteChrome><main className="search-page"><section className="search-card"><Link className="back" href="/library">← back</Link><p className="kicker">shared study desk</p><h1>find notes</h1><p className="sub">search public student notes by title.</p><div className="searchbar"><input autoFocus value={term} onChange={e=>{const v=e.target.value;setTerm(v);load(v)}} placeholder="e.g. data structures"/><button onClick={()=>load(term)}>{loading?'searching…':'search'}</button></div><div className="results">{results.map(note=><article key={note.id}><h2>{note.title}</h2><p>{String(note.body||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').slice(0,220)}{String(note.body||'').length>220?'…':''}</p><small>{note.authorName||'Stuko student'}</small></article>)}</div>{message&&<p className="message">{message}</p>}{searched&&<p className="hint">showing up to 50 relevant notes.</p>}</section></main><style jsx>{`.search-page{min-height:calc(100svh - 150px);padding:150px 20px 100px;display:grid;place-items:center}.search-card{width:min(900px,100%);padding:42px;border:1px solid var(--glass-border);border-radius:30px;background:var(--glass-bg);backdrop-filter:blur(12px);color:var(--page-text)}.back{display:inline-block;color:inherit;text-decoration:none;font:13px Arial;opacity:.65;margin-bottom:25px}.kicker{font:12px monospace;letter-spacing:.15em;text-transform:uppercase}.search-card h1{font-size:clamp(48px,7vw,80px);font-weight:400;letter-spacing:-.07em;margin:10px 0}.sub{opacity:.65}.searchbar{display:flex;gap:10px;margin-top:30px}.searchbar input{flex:1;min-width:0;border:1px solid var(--glass-border);border-radius:999px;background:transparent;color:inherit;padding:14px 18px;font:inherit;outline:none}.searchbar button{border:0;border-radius:999px;padding:14px 22px;background:var(--page-text);color:var(--page-bg);cursor:pointer}.results{display:grid;gap:12px;margin-top:28px}.results article{padding:20px;border:1px solid var(--glass-border);border-radius:20px;background:rgba(255,255,255,.05)}.results h2{margin:0 0 8px;font-size:21px}.results p{margin:0 0 12px;opacity:.72;line-height:1.6}.results small{opacity:.5}.message{opacity:.6;margin-top:22px}.hint{font:11px monospace;opacity:.4;margin-top:18px}@media(max-width:600px){.searchbar{flex-direction:column}}`}</style></SiteChrome>
}
