'use client';
import { useEffect, useState } from 'react';
import { addDoc, collection } from 'firebase/firestore';
import { firebaseConfigured, getFirebase } from '@/lib/firebase';
import SiteChrome from '@/app/components/SiteChrome';
export default function NotesPage(){
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[saved,setSaved]=useState(false),[publicNote,setPublicNote]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('stuko-notes');if(raw){const n=JSON.parse(raw);setTitle(n.title||'');setBody(n.body||'');setPublicNote(Boolean(n.public))}},[]);
 const save=async()=>{localStorage.setItem('stuko-notes',JSON.stringify({title,body,public:publicNote,updatedAt:new Date().toISOString()}));if(publicNote&&firebaseConfigured()&&title.trim()&&body.trim()){try{const {auth,db}=getFirebase();if(auth.currentUser){await addDoc(collection(db,'notes'),{title:title.trim(),body:body.trim(),authorId:auth.currentUser.uid,authorName:auth.currentUser.displayName||'Stuko student',createdAt:new Date(),public:true})}}catch{setStatus('saved locally · public sharing could not be synced')}}setSaved(true);setStatus(publicNote?'saved · public note':'saved privately');setTimeout(()=>{setSaved(false);setStatus('')},2200)};
 return <SiteChrome><main className="notes-page"><section className="notes-card"><p className="kicker">your study desk</p><h1>make notes</h1><p className="sub">write it down. save it. come back whenever you need it.</p><input className="title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="note title"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="start writing your notes..."/><div className="notes-bottom"><label><input type="checkbox" checked={publicNote} onChange={e=>setPublicNote(e.target.checked)}/> make this note discoverable by title</label><button onClick={save}>{saved?'saved ✓':'save note'}</button></div>{status&&<p className="status">{status}</p>}</section></main><style jsx>{`.notes-page{min-height:calc(100svh - 150px);padding:150px 20px 100px;display:grid;place-items:center}.notes-card{width:min(900px,100%);padding:42px;border:1px solid var(--glass-border);border-radius:30px;background:var(--glass-bg);backdrop-filter:blur(12px);color:var(--page-text)}.kicker{font:12px monospace;letter-spacing:.15em;text-transform:uppercase}.notes-card h1{font-size:clamp(48px,7vw,80px);font-weight:400;letter-spacing:-.07em;margin:10px 0}.sub{opacity:.65}.title,textarea{width:100%;box-sizing:border-box;border:1px solid var(--glass-border);border-radius:16px;background:transparent;color:inherit;padding:15px 17px;font:inherit;outline:none}.title{margin-top:30px;font-size:20px}.notes-card textarea{margin-top:12px;min-height:420px;resize:vertical;line-height:1.7}.notes-bottom{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-top:14px;flex-wrap:wrap;font-size:13px}.notes-bottom button{border:0;border-radius:999px;padding:12px 22px;background:var(--page-text);color:var(--page-bg);cursor:pointer}.status{opacity:.65;font-size:13px;margin-top:14px}`}</style></SiteChrome>
}