'use client';

import { FormEvent, useEffect, useState } from 'react';
import { onAuthStateChanged, reauthenticateWithPopup, updatePassword } from 'firebase/auth';
import { doc, getDoc, runTransaction, serverTimestamp } from 'firebase/firestore';
import { firebaseConfigured, getFirebase, googleProvider } from '../../lib/firebase';
import { useRouter } from 'next/navigation';
import styles from './onboarding.module.css';

export default function OnboardingPage(){
  const router=useRouter(); const [userId,setUserId]=useState(''); const [email,setEmail]=useState(''); const [username,setUsername]=useState(''); const [displayName,setDisplayName]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{if(!firebaseConfigured()){setError('Firebase is not configured yet.');return;} const {auth,db}=getFirebase(); return onAuthStateChanged(auth,async user=>{if(!user){router.replace('/auth');return;} setUserId(user.uid);setEmail(user.email||'');const snap=await getDoc(doc(db,'users',user.uid));if(snap.exists()&&snap.data().username) router.replace('/profile');});},[router]);
  async function submit(e:FormEvent){e.preventDefault();setError('');const clean=username.trim().toLowerCase();if(!/^[a-z_.]+$/.test(clean)){setError('Username can only use lowercase letters, underscores (_) and periods (.).');return;}if(clean.length<3){setError('Username must be at least 3 characters.');return;}if(displayName.trim().length<2){setError('Add a display name.');return;}if(password.length<8){setError('Password must be at least 8 characters.');return;}if(password!==confirm){setError('Passwords do not match.');return;}setLoading(true);try{const {auth,db}=getFirebase();const currentUser=auth.currentUser;if(!currentUser)throw new Error('Session expired. Please sign in again.');if(currentUser.providerData.some(provider=>provider.providerId==='google.com')){await reauthenticateWithPopup(currentUser,googleProvider());}await updatePassword(currentUser,password);await runTransaction(db,async tx=>{const userRef=doc(db,'users',userId);const nameRef=doc(db,'usernames',clean);const existing=await tx.get(nameRef);if(existing.exists()&&existing.data().uid!==userId)throw new Error('That username is already taken. Try another one.');tx.set(nameRef,{uid:userId,username:clean},{merge:true});tx.set(userRef,{uid:userId,email,username:clean,displayName:displayName.trim(),bio:'',photoURL:currentUser.photoURL||'',followersCount:0,followingCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});});router.replace('/profile');}catch(e){setError(e instanceof Error?e.message:'Could not create your profile.');}finally{setLoading(false);}}
  function handleUsernameChange(value:string){setUsername(value.toLowerCase().replace(/[^a-z_.]/g,''));}
  return <main className={styles.page}><div className={styles.card}><div className={styles.logo}><span>S</span> STUKO</div><p className={styles.eyebrow}>ONE LAST THING</p><h1>Make it yours.</h1><p className={styles.sub}>Your Google account is connected. Now choose how people will know you on STUKO.</p><form className={styles.form} onSubmit={submit}><label className={styles.field}>Username <small>public</small><input className={styles.input} value={username} onChange={e=>handleUsernameChange(e.target.value)} placeholder="" autoComplete="username"/></label><label className={styles.field}>Display name<input className={styles.input} value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder=""/></label><label className={styles.field}>Password<input className={styles.input} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="" autoComplete="new-password"/></label><label className={styles.field}>Confirm password<input className={styles.input} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="" autoComplete="new-password"/></label>{error&&<p className={styles.error}>{error}</p>}<button className={styles.submit} disabled={loading||!userId}>{loading?'Creating your universe…':'Create my profile ✦'}</button></form><p className={styles.note}>Your password is handled by Firebase Authentication — STUKO never stores it in your profile database.</p></div></main>;
}
