'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, query, serverTimestamp, setDoc, where } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { Bell, BookOpen, BarChart3, Globe2, Lock, Menu, MessageCircle, Plus, Search, Settings, Send, UserCheck, UserPlus, X, Check, Sun, Moon, Monitor, Sparkles, Palette } from 'lucide-react';
import { firebaseConfigured, getFirebase } from '../../../lib/firebase';
import { useTheme, ThemeName } from '../../theme-provider';
import styles from './public.module.css';

type Profile={username:string;displayName:string;bio:string;photoURL:string;followersCount:number;followingCount:number;createdAt?:any};
type WallPost={id:string;authorUid:string;authorUsername:string;authorDisplayName:string;authorPhotoURL:string;text:string;createdAt?:any;profileUid:string};
type CollectionItem={id:string;ownerUid:string;title:string;subject:string;description?:string;isPublic:boolean;createdAt?:any};
type Person={uid:string;username:string;displayName:string;photoURL:string};
type ReadItem={id:string;title:string;subject:string;readAt?:any};
type NoteComment={id:string;noteTitle?:string;text:string;createdAt?:any};
type Activity={id:string;date:any;chapters:number};

const tabs=['Wall','Collections','Recent reads','Comments','Followers','Following','Stats'];
const themeChoices:{id:ThemeName;name:string;description:string;icon:any}[]=[
 {id:'light',name:'Basic light',description:'White background · black text',icon:Sun},
 {id:'dark',name:'Basic dark',description:'Black background · white text',icon:Moon},
 {id:'system',name:'Default',description:'Follow your system setting',icon:Monitor},
 {id:'pink',name:'Baby pink light',description:'Soft pastel pink · whimsical',icon:Sparkles},
 {id:'purple',name:'Purple dark',description:'Deep purple · light text',icon:Palette},
];
const emptyCopy={
 'Collections':['No public collections yet.','Collections are where subjects you love get their own little corner.'],
 'Recent reads':['No recent reads yet.','Once you start studying, your latest subjects will show up here.'],
 'Comments':['No comments yet.','Comments this person leaves on other notes will appear here.'],
 'Followers':['No followers yet.','When people follow this profile, they will appear here.'],
 'Following':['Not following anyone yet.','Profiles this person follows will appear here.'],
};
function toDate(value:any){if(!value)return null;const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?null:d;}
function dateLabel(value:any){const d=toDate(value);if(!d)return 'just now';const diff=Math.max(0,Date.now()-d.getTime());const mins=Math.floor(diff/60000);if(mins<1)return 'just now';if(mins<60)return `${mins}m ago`;const hrs=Math.floor(mins/60);if(hrs<24)return `${hrs}h ago`;const days=Math.floor(hrs/24);if(days<30)return `${days}d ago`;return d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});}
function joinedLabel(value:any){const d=toDate(value);return d?`Joined ${d.toLocaleDateString(undefined,{month:'short',year:'numeric'})}`:'Joined recently';}

export default function PublicProfile({params}:{params:Promise<{username:string}>}){
 const {theme,setTheme}=useTheme();
 const [profile,setProfile]=useState<Profile|null>(null);const [uid,setUid]=useState('');const [viewerUid,setViewerUid]=useState('');const [active,setActive]=useState('Wall');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [wall,setWall]=useState<WallPost[]>([]);const [collections,setCollections]=useState<CollectionItem[]>([]);const [reads,setReads]=useState<ReadItem[]>([]);const [comments,setComments]=useState<NoteComment[]>([]);const [people,setPeople]=useState<Person[]>([]);const [message,setMessage]=useState('');const [wallText,setWallText]=useState('');const [followed,setFollowed]=useState(false);const [showCreate,setShowCreate]=useState(false);const [newCollection,setNewCollection]=useState({title:'',subject:'',description:'',isPublic:true});const [activity,setActivity]=useState<Activity[]>([]);const [mobileOpen,setMobileOpen]=useState(false);const [showThemes,setShowThemes]=useState(false);
 useEffect(()=>{if(!firebaseConfigured()){setError('Profile database is not configured yet.');setLoading(false);return;}const {auth,db}=getFirebase();const unsub=onAuthStateChanged(auth,user=>setViewerUid(user?.uid||''));params.then(async p=>{const clean=p.username.toLowerCase();try{const nameSnap=await getDoc(doc(db,'usernames',clean));if(!nameSnap.exists())throw new Error('This profile does not exist.');const profileUid=nameSnap.data().uid as string;const userSnap=await getDoc(doc(db,'users',profileUid));if(!userSnap.exists())throw new Error('This profile does not exist.');setUid(profileUid);setProfile(userSnap.data() as Profile);await loadAll(db,profileUid,'');}catch(e){setError(e instanceof Error?e.message:'Could not load profile.');}finally{setLoading(false);}});return unsub;},[params]);
 async function loadAll(db:any,profileUid:string,viewer:string){
  const wallSnap=await getDocs(query(collection(db,'wallPosts'),where('profileUid','==',profileUid))).catch(()=>null);if(wallSnap)setWall((wallSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as WallPost[]).sort((a,b)=>(toDate(b.createdAt)?.getTime()||0)-(toDate(a.createdAt)?.getTime()||0)));
  const colSnap=viewer===profileUid?await getDocs(query(collection(db,'collections'),where('ownerUid','==',profileUid))).catch(()=>null):await getDocs(query(collection(db,'collections'),where('ownerUid','==',profileUid),where('isPublic','==',true))).catch(()=>null);if(colSnap){const all=colSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as CollectionItem[];setCollections(all.sort((a,b)=>(toDate(b.createdAt)?.getTime()||0)-(toDate(a.createdAt)?.getTime()||0)));}
  const readSnap=await getDocs(query(collection(db,'reads'),where('uid','==',profileUid))).catch(()=>null);if(readSnap)setReads((readSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as ReadItem[]).sort((a,b)=>(toDate(b.readAt)?.getTime()||0)-(toDate(a.readAt)?.getTime()||0)));
  const commentSnap=await getDocs(query(collection(db,'noteComments'),where('authorUid','==',profileUid))).catch(()=>null);if(commentSnap)setComments((commentSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as NoteComment[]).sort((a,b)=>(toDate(b.createdAt)?.getTime()||0)-(toDate(a.createdAt)?.getTime()||0)));
  const followerSnap=await getDocs(query(collection(db,'follows'),where('followingUid','==',profileUid))).catch(()=>null);const followingSnap=await getDocs(query(collection(db,'follows'),where('followerUid','==',profileUid))).catch(()=>null);const selected=active==='Followers'?followerSnap:followingSnap;if(selected){const ids=selected.docs.map((d:any)=>active==='Followers'?d.data().followerUid:d.data().followingUid);setPeople(await getPeople(db,ids));setProfile(p=>p?{...p,followersCount:followerSnap?.size||0,followingCount:followingSnap?.size||0}:p);}
  if(viewer&&viewer!==profileUid){const followSnap=await getDoc(doc(db,'follows',`${viewer}_${profileUid}`));setFollowed(followSnap.exists());}
  const activitySnap=await getDocs(query(collection(db,'studyActivity'),where('uid','==',profileUid))).catch(()=>null);if(activitySnap)setActivity(activitySnap.docs.map((d:any)=>({id:d.id,...d.data()})) as Activity[]);
 }
 async function getPeople(db:any,ids:string[]){return Promise.all(ids.slice(0,100).map(async id=>{const s=await getDoc(doc(db,'users',id));return s.exists()?({uid:id,...s.data()} as Person):null})).then(x=>x.filter(Boolean) as Person[]);}
 useEffect(()=>{if(uid&&profile&&firebaseConfigured()){const {db}=getFirebase();loadAll(db,uid,viewerUid).catch(()=>{});}},[active,uid,viewerUid]);
 async function postWall(e:FormEvent){e.preventDefault();if(!viewerUid||!wallText.trim()||!uid)return;setBusy(true);setMessage('');try{const {db}=getFirebase();const me=await getDoc(doc(db,'users',viewerUid));const m=me.data()||{};const ref=await addDoc(collection(db,'wallPosts'),{profileUid:uid,authorUid:viewerUid,authorUsername:m.username||'student',authorDisplayName:m.displayName||'Student',authorPhotoURL:m.photoURL||'',text:wallText.trim(),createdAt:serverTimestamp()});setWall(w=>[{id:ref.id,profileUid:uid,authorUid:viewerUid,authorUsername:m.username||'student',authorDisplayName:m.displayName||'Student',authorPhotoURL:m.photoURL||'',text:wallText.trim()} as WallPost,...w]);setWallText('');}catch(e){setMessage(e instanceof Error?e.message:'Could not post. Check Firestore rules.');}finally{setBusy(false);}}
 async function toggleFollow(){if(!viewerUid||viewerUid===uid)return;setBusy(true);try{const {db}=getFirebase();const ref=doc(db,'follows',`${viewerUid}_${uid}`);if(followed){await deleteDoc(ref);setFollowed(false);setProfile(p=>p?{...p,followersCount:Math.max(0,(p.followersCount||0)-1)}:p);}else{await setDoc(ref,{followerUid:viewerUid,followingUid:uid,createdAt:serverTimestamp()});setFollowed(true);setProfile(p=>p?{...p,followersCount:(p.followersCount||0)+1}:p);}}catch(e){setMessage(e instanceof Error?e.message:'Could not update follow.');}finally{setBusy(false);}}
 async function createCollection(e:FormEvent){e.preventDefault();if(!viewerUid||viewerUid!==uid||!newCollection.title.trim()||!newCollection.subject.trim())return;setBusy(true);try{const {db}=getFirebase();const ref=await addDoc(collection(db,'collections'),{ownerUid:uid,title:newCollection.title.trim(),subject:newCollection.subject.trim(),description:newCollection.description.trim(),isPublic:newCollection.isPublic,createdAt:serverTimestamp()});setCollections(c=>[{id:ref.id,ownerUid:uid,...newCollection,title:newCollection.title.trim(),subject:newCollection.subject.trim(),description:newCollection.description.trim()} as CollectionItem,...c]);setNewCollection({title:'',subject:'',description:'',isPublic:true});setShowCreate(false);}catch(e){setMessage(e instanceof Error?e.message:'Could not create collection. Check Firestore rules.');}finally{setBusy(false);}}
 const totals=useMemo(()=>{const now=Date.now();const day=86400000;const vals=activity.map(a=>({date:toDate(a.date),chapters:Number(a.chapters)||0})).filter(x=>x.date);const today=vals.filter(x=>x.date!.toDateString()===new Date().toDateString()).reduce((s,x)=>s+x.chapters,0);const week=vals.filter(x=>now-x.date!.getTime()<7*day).reduce((s,x)=>s+x.chapters,0);const month=vals.filter(x=>now-x.date!.getTime()<30*day).reduce((s,x)=>s+x.chapters,0);const all=vals.reduce((s,x)=>s+x.chapters,0);let streak=0;for(let i=0;i<370;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);if(vals.some(x=>x.date!.toDateString()===d.toDateString()&&x.chapters>0))streak++;else if(i>0)break;}return {today,week,month,all,streak};},[activity]);
 const chart=useMemo(()=>{const now=new Date();now.setHours(0,0,0,0);return Array.from({length:30},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-(29-i));return activity.filter(a=>{const x=toDate(a.date);return x?.toDateString()===d.toDateString()}).reduce((s,a)=>s+(Number(a.chapters)||0),0);});},[activity]);
 const chartMax=Math.max(1,...chart);const points=chart.map((v,i)=>`${(i/29)*100},${100-(v/chartMax)*82-5}`).join(' ');
 const heat=useMemo(()=>Array.from({length:364},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(363-i));return activity.filter(a=>toDate(a.date)?.toDateString()===d.toDateString()).reduce((s,a)=>s+(Number(a.chapters)||0),0);}),[activity]);
 const genres=useMemo(()=>{const counts=new Map<string,number>();collections.forEach(c=>counts.set(c.subject,(counts.get(c.subject)||0)+1));const rows=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);return rows.length?rows.map(([name,n])=>[name,n]):[['No subjects yet',0],['Computer Science',0],['Languages',0],['Design',0],['History',0]];},[collections]);
 const genreMax=Math.max(1,...genres.map(x=>Number(x[1])));const libraryTotal=Math.max(1,collections.length+reads.length);const reading=reads.length;const completed=Math.max(0,collections.filter(c=>c.isPublic).length);const onHold=Math.max(0,collections.filter(c=>!c.isPublic).length);const dropped=0;const plan=Math.max(0,libraryTotal-reading-completed-onHold);const donut=`conic-gradient(#9568ff 0 ${reading/libraryTotal*100}%,#43d78a ${reading/libraryTotal*100}% ${(reading+completed)/libraryTotal*100}%,#e5bd3a ${(reading+completed)/libraryTotal*100}% ${(reading+completed+onHold)/libraryTotal*100}%,#e86e78 ${(reading+completed+onHold)/libraryTotal*100}% ${(reading+completed+onHold+dropped)/libraryTotal*100}%,#5798ea ${(reading+completed+onHold+dropped)/libraryTotal*100}% 100%)`;
 if(loading)return <main className={styles.page}><div className={styles.loading}>Loading profile…</div></main>;
 if(error||!profile)return <main className={styles.page}><div className={styles.missing}><span>✦</span><h1>{error||'Profile not found.'}</h1><a href="/">Back to STUKO</a></div></main>;
 return <main className={styles.page}><div className={styles.wrap}>
  <header className={styles.top}><a href="/" className={styles.brand}><span className={styles.brandMark}>S</span>STUKO</a><div className={styles.search}><Search size={17}/><input placeholder="Search any title..."/><button>Browse</button></div><div className={styles.headerActions}><button aria-label="Themes" title="Themes" onClick={()=>setShowThemes(v=>!v)}><Settings size={21}/></button><button onClick={()=>setMobileOpen(v=>!v)} aria-label="Menu">{mobileOpen?<X size={22}/>:<Menu size={22}/>}</button><button aria-label="Notifications"><Bell size={21}/></button><a href="/profile" className={styles.headerAvatar}>{profile.photoURL?<img src={profile.photoURL} alt=""/>:profile.displayName?.[0]?.toUpperCase()||'S'}</a></div>{showThemes&&<div className={styles.themePopover}><div className={styles.themeTitle}>Themes</div>{themeChoices.map(t=>{const Icon=t.icon;return <button key={t.id} className={`${styles.themeOption} ${theme===t.id?styles.selected:''}`} onClick={()=>{setTheme(t.id);setShowThemes(false)}}><span className={styles.themeDot}><Icon size={13}/></span><span><b>{t.name}</b><small>{t.description}</small></span>{theme===t.id&&<Check size={14}/>}</button>})}</div>}</header>
  <div className={styles.crumb}>HOME <span>/</span> {profile.username.toUpperCase()}</div>
  <section className={styles.hero}><div className={styles.avatar}>{profile.photoURL?<img src={profile.photoURL} alt=""/>:profile.displayName?.[0]?.toUpperCase()||'S'}</div><div className={styles.identity}><h1>{profile.displayName}<span>✦</span></h1><p className={styles.joined}>{joinedLabel(profile.createdAt)}</p><p className={styles.bio}>{profile.bio||':)'}</p><div className={styles.stats}><button onClick={()=>setActive('Followers')}><b>{profile.followersCount||0}</b> followers</button><button onClick={()=>setActive('Following')}><b>{profile.followingCount||0}</b> following</button><span><b>{collections.length}</b> collections</span><span><b>{comments.length}</b> comments</span><span><b>{reads.length}</b> titles followed</span><span><b>{totals.all.toLocaleString()}</b> chapters read</span></div></div><div className={styles.heroActions}>{viewerUid&&viewerUid!==uid&&<button className={followed?styles.following:styles.follow} onClick={toggleFollow} disabled={busy}>{followed?<><UserCheck size={15}/> Following</>:<><UserPlus size={15}/> Follow</>}</button>}</div></section>
  <nav className={styles.menu}>{tabs.map(tab=><button key={tab} onClick={()=>setActive(tab)} className={active===tab?styles.active:''}>{tab}</button>)}</nav>
  {message&&<div className={styles.message}>{message}</div>}
  {active==='Wall'&&<section className={styles.wallSection}><div className={styles.notice}><span>ⓘ</span> Note: Please take a moment to <b>read the comment rules</b> before posting!</div><div className={styles.wallToolbar}><span>{wall.length} comments</span><div><button>Best</button><button>Newest</button><button>Oldest</button></div></div>{viewerUid&&<form className={styles.composer} onSubmit={postWall}><div className={styles.smallAvatar}>{profile.photoURL?<img src={profile.photoURL} alt=""/>:profile.displayName?.[0]?.toUpperCase()||'S'}</div><textarea value={wallText} onChange={e=>setWallText(e.target.value)} placeholder="Write something on this wall..." maxLength={500}/><button disabled={busy||!wallText.trim()}><Send size={15}/></button></form>}{wall.length===0?<div className={styles.empty}><div>♡</div><h3>No comments yet.</h3><p>Be the first person to leave something nice.</p></div>:<div className={styles.wallList}>{wall.map(post=><article className={styles.note} key={post.id}><div className={styles.smallAvatar}>{post.authorPhotoURL?<img src={post.authorPhotoURL} alt=""/>:post.authorDisplayName?.[0]?.toUpperCase()||'S'}</div><div className={styles.noteBody}><div className={styles.noteMeta}><b>{post.authorDisplayName}</b><span>{dateLabel(post.createdAt)}</span></div><p>{post.text}</p><div className={styles.noteActions}>♡ 0 &nbsp;&nbsp; ↩ Reply &nbsp;&nbsp; ··· More</div></div></article>)}</div>}</section>}
  {active==='Collections'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>SUBJECT COLLECTIONS</p><h2>Collections</h2><span>Study spaces curated around what {profile.displayName} loves.</span></div><BookOpen size={21}/></div>{viewerUid===uid&&<button className={styles.create} onClick={()=>setShowCreate(v=>!v)}><Plus size={15}/> New collection</button>}{showCreate&&viewerUid===uid&&<form className={styles.createForm} onSubmit={createCollection}><input placeholder="Collection name" value={newCollection.title} onChange={e=>setNewCollection({...newCollection,title:e.target.value})}/><input placeholder="Subject" value={newCollection.subject} onChange={e=>setNewCollection({...newCollection,subject:e.target.value})}/><input placeholder="Short description" value={newCollection.description} onChange={e=>setNewCollection({...newCollection,description:e.target.value})}/><label><input type="checkbox" checked={newCollection.isPublic} onChange={e=>setNewCollection({...newCollection,isPublic:e.target.checked})}/>{newCollection.isPublic?<><Globe2 size={14}/> Public</>:<><Lock size={14}/> Private</>}</label><button disabled={busy}>Create collection ✦</button></form>}{collections.length===0?<div className={styles.empty}><div>◌</div><h3>{emptyCopy.Collections[0]}</h3><p>{emptyCopy.Collections[1]}</p></div>:<div className={styles.grid}>{collections.map(c=><article className={styles.collection} key={c.id}><div className={styles.collectionIcon}>✦</div><div><span className={styles.collectionTag}>{c.isPublic?'PUBLIC':'PRIVATE'}</span><h3>{c.title}</h3><b>{c.subject}</b><p>{c.description||'A little study universe.'}</p></div></article>)}</div>}</section>}
  {active==='Recent reads'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>RECENT ACTIVITY</p><h2>Recent reads</h2><span>The subjects and study material read most recently.</span></div><BookOpen size={21}/></div>{reads.length===0?<div className={styles.empty}><div>⌁</div><h3>{emptyCopy['Recent reads'][0]}</h3><p>{emptyCopy['Recent reads'][1]}</p></div>:<div className={styles.readList}>{reads.map(r=><div className={styles.read} key={r.id}><div className={styles.readIcon}><BookOpen size={16}/></div><div><b>{r.title}</b><span>{r.subject}</span></div><time>{dateLabel(r.readAt)}</time></div>)}</div>}</section>}
  {active==='Comments'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>PUBLIC ACTIVITY</p><h2>Comments</h2><span>Comments made on other people's notes.</span></div><MessageCircle size={21}/></div>{comments.length===0?<div className={styles.empty}><div>♡</div><h3>{emptyCopy.Comments[0]}</h3><p>{emptyCopy.Comments[1]}</p></div>:<div className={styles.commentList}>{comments.map(c=><article className={styles.comment} key={c.id}><MessageCircle size={16}/><div><p>{c.text}</p><span>{c.noteTitle||'On a study note'} · {dateLabel(c.createdAt)}</span></div></article>)}</div>}</section>}
  {(active==='Followers'||active==='Following')&&<section className={styles.panel}><div className={styles.panelHead}><div><p>COMMUNITY</p><h2>{active}</h2><span>{active==='Followers'?'People who follow this profile.':'People this profile follows.'}</span></div></div>{people.length===0?<div className={styles.empty}><div>♡</div><h3>{emptyCopy[active][0]}</h3><p>{emptyCopy[active][1]}</p></div>:<div className={styles.people}>{people.map(p=><a className={styles.person} href={`/u/${p.username}`} key={p.uid}><div className={styles.smallAvatar}>{p.photoURL?<img src={p.photoURL} alt=""/>:p.displayName?.[0]?.toUpperCase()||'S'}</div><div><b>{p.displayName}</b><span>@{p.username}</span></div><span className={styles.view}>View →</span></a>)}</div>}</section>}
  {active==='Stats'&&<section className={styles.statsPage}><div className={styles.statsHeader}><div><p>READING ACTIVITY</p><h2>Stats</h2></div><BarChart3 size={20}/></div><div className={styles.statCards}>{[['TODAY',totals.today,'chapters'],['THIS WEEK',totals.week,'chapters · 7d'],['THIS MONTH',totals.month,'chapters · 30d'],['ALL-TIME',totals.all,'chapters'],['CURRENT STREAK',totals.streak,'days']].map(([label,value,sub])=><div className={styles.statCard} key={String(label)}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong><small>{sub}</small></div>)}</div><div className={styles.statsGrid}><div className={styles.chartCard}><p>LAST 30 DAYS</p><strong>{totals.month.toLocaleString()}</strong><span> chapters in the last 30 days</span><div className={styles.lineChart}><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" y1="95" x2="100" y2="95"/><line x1="0" y1="52" x2="100" y2="52"/><line x1="0" y1="5" x2="100" y2="5"/><polyline points={points}/></svg></div><div className={styles.axis}><span>30 days ago</span><span>Today</span></div></div><div className={styles.chartCard}><p>LAST 12 MONTHS</p><div className={styles.monthLabels}>{['Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map(m=><span key={m}>{m}</span>)}</div><div className={styles.heatmap}>{heat.map((n,i)=><i key={i} className={n>12?'hot4':n>7?'hot3':n>3?'hot2':n>0?'hot1':''}/>)}</div><div className={styles.legend}>Less <i></i><i className="hot1"></i><i className="hot2"></i><i className="hot3"></i><i className="hot4"></i> More</div></div><div className={styles.chartCard}><p>TOP GENRES FOLLOWED</p><div className={styles.genreList}>{genres.map(([name,n])=><div className={styles.barRow} key={String(name)}><span>{name}</span><i><em style={{width:`${(Number(n)/genreMax)*100}%`}}/></i><b>{n}</b></div>)}</div></div><div className={styles.chartCard}><p>LIBRARY STATUS</p><div className={styles.library}><div className={styles.donut} style={{background:donut}}><span>{libraryTotal}</span><small>titles</small></div><div className={styles.libraryLegend}><span><i/>Reading <b>{reading}</b></span><span><i/>Completed <b>{completed}</b></span><span><i/>On hold <b>{onHold}</b></span><span><i/>Dropped <b>{dropped}</b></span><span><i/>Plan to read <b>{plan}</b></span></div></div></div></div></section>}
  <footer className={styles.footer}>STUKO · study, but make it yours.</footer>
 </div></main>;
}
