'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, query, serverTimestamp, setDoc, where } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { firebaseConfigured, getFirebase } from '../../../lib/firebase';
import { MessageCircle, UserPlus, UserCheck, BookOpen, BarChart3, Lock, Globe2, Plus, Send, Users } from 'lucide-react';
import styles from './public.module.css';

type Profile={username:string;displayName:string;bio:string;photoURL:string;followersCount:number;followingCount:number;createdAt?:any};
type WallPost={id:string;authorUid:string;authorUsername:string;authorDisplayName:string;authorPhotoURL:string;text:string;createdAt?:any;profileUid:string};
type CollectionItem={id:string;ownerUid:string;title:string;subject:string;description?:string;isPublic:boolean;createdAt?:any};
type Person={uid:string;username:string;displayName:string;photoURL:string};
type ReadItem={id:string;title:string;subject:string;readAt?:any};
type NoteComment={id:string;noteTitle?:string;text:string;createdAt?:any};
type Activity={id:string;date:any;chapters:number};

const tabs=['Wall','Collections','Recent reads','Comments','Followers','Following','Stats'];
const emptyCopy={
  'Collections':['No public collections yet.','Collections are where subjects you love get their own little corner.'],
  'Recent reads':['No recent reads yet.','Once you start studying, your latest subjects will show up here.'],
  'Comments':['No comments yet.','Comments this person leaves on other notes will appear here.'],
  'Followers':['No followers yet.','When people follow this profile, they will appear here.'],
  'Following':['Not following anyone yet.','Profiles this person follows will appear here.'],
};

function dateLabel(value:any){if(!value)return 'just now';const d=value?.toDate?value.toDate():new Date(value);if(Number.isNaN(d.getTime()))return 'recently';const diff=Math.max(0,Date.now()-d.getTime());const mins=Math.floor(diff/60000);if(mins<1)return 'just now';if(mins<60)return `${mins}m ago`;const hrs=Math.floor(mins/60);if(hrs<24)return `${hrs}h ago`;const days=Math.floor(hrs/24);if(days<30)return `${days}d ago`;return d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});}

export default function PublicProfile({params}:{params:Promise<{username:string}>}){
 const [profile,setProfile]=useState<Profile|null>(null);const [uid,setUid]=useState('');const [viewerUid,setViewerUid]=useState('');const [active,setActive]=useState('Wall');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [wall,setWall]=useState<WallPost[]>([]);const [collections,setCollections]=useState<CollectionItem[]>([]);const [reads,setReads]=useState<ReadItem[]>([]);const [comments,setComments]=useState<NoteComment[]>([]);const [people,setPeople]=useState<Person[]>([]);const [message,setMessage]=useState('');const [wallText,setWallText]=useState('');const [followed,setFollowed]=useState(false);const [showCreate,setShowCreate]=useState(false);const [newCollection,setNewCollection]=useState({title:'',subject:'',description:'',isPublic:true});const [activity,setActivity]=useState<Activity[]>([]);

 useEffect(()=>{if(!firebaseConfigured()){setError('Profile database is not configured yet.');setLoading(false);return;}const {auth,db}=getFirebase();const unsub=onAuthStateChanged(auth,user=>setViewerUid(user?.uid||''));params.then(async p=>{const clean=p.username.toLowerCase();try{const nameSnap=await getDoc(doc(db,'usernames',clean));if(!nameSnap.exists())throw new Error('This profile does not exist.');const profileUid=nameSnap.data().uid as string;const userSnap=await getDoc(doc(db,'users',profileUid));if(!userSnap.exists())throw new Error('This profile does not exist.');setUid(profileUid);setProfile(userSnap.data() as Profile);await loadAll(db,profileUid,'');}catch(e){setError(e instanceof Error?e.message:'Could not load profile.');}finally{setLoading(false);}});return unsub;},[params]);

 async function loadAll(db:any,profileUid:string,viewer:string){
  const wallSnap=await getDocs(query(collection(db,'wallPosts'),where('profileUid','==',profileUid))).catch(()=>null);if(wallSnap)setWall((wallSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as WallPost[]).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));
  const colSnap=viewer===profileUid?await getDocs(query(collection(db,'collections'),where('ownerUid','==',profileUid))).catch(()=>null):await getDocs(query(collection(db,'collections'),where('ownerUid','==',profileUid),where('isPublic','==',true))).catch(()=>null);if(colSnap){const all=colSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as CollectionItem[];setCollections(all.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));}
  const readSnap=await getDocs(query(collection(db,'reads'),where('uid','==',profileUid))).catch(()=>null);if(readSnap)setReads((readSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as ReadItem[]).sort((a,b)=>(b.readAt?.seconds||0)-(a.readAt?.seconds||0)));
  const commentSnap=await getDocs(query(collection(db,'noteComments'),where('authorUid','==',profileUid))).catch(()=>null);if(commentSnap)setComments((commentSnap.docs.map((d:any)=>({id:d.id,...d.data()})) as NoteComment[]).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));
  const followerSnap=await getDocs(query(collection(db,'follows'),where('followingUid','==',profileUid))).catch(()=>null);const followingSnap=await getDocs(query(collection(db,'follows'),where('followerUid','==',profileUid))).catch(()=>null);
  const selected=active==='Followers'?followerSnap:followingSnap;if(selected){const ids=selected.docs.map((d:any)=>active==='Followers'?d.data().followerUid:d.data().followingUid);setPeople(await getPeople(db,ids));setProfile(p=>p?{...p,followersCount:followerSnap?.size||0,followingCount:followingSnap?.size||0}:p);}
  if(viewer&&viewer!==profileUid){const followSnap=await getDoc(doc(db,'follows',`${viewer}_${profileUid}`));setFollowed(followSnap.exists());}
  const activitySnap=await getDocs(query(collection(db,'studyActivity'),where('uid','==',profileUid))).catch(()=>null);if(activitySnap)setActivity(activitySnap.docs.map((d:any)=>({id:d.id,...d.data()})) as Activity[]);
 }
 async function getPeople(db:any,ids:string[]){return Promise.all(ids.slice(0,100).map(async id=>{const s=await getDoc(doc(db,'users',id));return s.exists()?({uid:id,...s.data()} as Person):null})).then(x=>x.filter(Boolean) as Person[]);}
 useEffect(()=>{if(uid&&profile&&firebaseConfigured()){const {db}=getFirebase();loadAll(db,uid,viewerUid).catch(()=>{});}},[active,uid,viewerUid]);

 async function postWall(e:FormEvent){e.preventDefault();if(!viewerUid||!wallText.trim()||!uid)return;setBusy(true);setMessage('');try{const {db}=getFirebase();const me=await getDoc(doc(db,'users',viewerUid));const m=me.data()||{};const ref=await addDoc(collection(db,'wallPosts'),{profileUid:uid,authorUid:viewerUid,authorUsername:m.username||'student',authorDisplayName:m.displayName||'Student',authorPhotoURL:m.photoURL||'',text:wallText.trim(),createdAt:serverTimestamp()});setWall(w=>[{id:ref.id,profileUid:uid,authorUid:viewerUid,authorUsername:m.username||'student',authorDisplayName:m.displayName||'Student',authorPhotoURL:m.photoURL||'',text:wallText.trim()} as WallPost,...w]);setWallText('');}catch(e){setMessage(e instanceof Error?e.message:'Could not post. Check Firestore rules.');}finally{setBusy(false);}}
 async function toggleFollow(){if(!viewerUid||viewerUid===uid)return;setBusy(true);try{const {db}=getFirebase();const ref=doc(db,'follows',`${viewerUid}_${uid}`);if(followed){await deleteDoc(ref);setFollowed(false);setProfile(p=>p?{...p,followersCount:Math.max(0,(p.followersCount||0)-1)}:p);}else{await setDoc(ref,{followerUid:viewerUid,followingUid:uid,createdAt:serverTimestamp()});setFollowed(true);setProfile(p=>p?{...p,followersCount:(p.followersCount||0)+1}:p);}}catch(e){setMessage(e instanceof Error?e.message:'Could not update follow.');}finally{setBusy(false);}}
 async function createCollection(e:FormEvent){e.preventDefault();if(!viewerUid||viewerUid!==uid||!newCollection.title.trim()||!newCollection.subject.trim())return;setBusy(true);try{const {db}=getFirebase();const ref=await addDoc(collection(db,'collections'),{ownerUid:uid,title:newCollection.title.trim(),subject:newCollection.subject.trim(),description:newCollection.description.trim(),isPublic:newCollection.isPublic,createdAt:serverTimestamp()});setCollections(c=>[{id:ref.id,ownerUid:uid,...newCollection,title:newCollection.title.trim(),subject:newCollection.subject.trim(),description:newCollection.description.trim()} as CollectionItem,...c]);setNewCollection({title:'',subject:'',description:'',isPublic:true});setShowCreate(false);}catch(e){setMessage(e instanceof Error?e.message:'Could not create collection. Check Firestore rules.');}finally{setBusy(false);}}

 const totals=useMemo(()=>{const now=Date.now();const day=86400000;const vals=activity.map(a=>({date:a.date?.toDate?a.date.toDate():new Date(a.date),chapters:Number(a.chapters)||0}));const today=vals.filter(x=>now-x.date.getTime()<day&&x.date.toDateString()===new Date().toDateString()).reduce((s,x)=>s+x.chapters,0);const week=vals.filter(x=>now-x.date.getTime()<7*day).reduce((s,x)=>s+x.chapters,0);const month=vals.filter(x=>now-x.date.getTime()<30*day).reduce((s,x)=>s+x.chapters,0);const all=vals.reduce((s,x)=>s+x.chapters,0);let streak=0;for(let i=0;i<60;i++){const d=new Date();d.setDate(d.getDate()-i);if(vals.some(x=>x.date.toDateString()===d.toDateString()&&x.chapters>0))streak++;else if(i>0)break;}return {today,week,month,all,streak};},[activity]);

 if(loading)return <main className={styles.page}><div className={styles.loading}>Loading profile…</div></main>;
 if(error||!profile)return <main className={styles.page}><div className={styles.missing}><span>✦</span><h1>{error||'Profile not found.'}</h1><a href="/">Back to STUKO</a></div></main>;
 return <main className={styles.page}><div className={styles.wrap}>
  <header className={styles.top}><a href="/" className={styles.brand}>STUKO</a><div className={styles.actions}>{viewerUid&&viewerUid!==uid&&<button className={followed?styles.following:styles.follow} onClick={toggleFollow} disabled={busy}>{followed?<><UserCheck size={15}/> Following</>:<><UserPlus size={15}/> Follow</>}</button>}<a href="/profile" className={styles.edit}>Edit profile</a></div></header>
  <div className={styles.crumb}>HOME <span>/</span> {profile.username.toUpperCase()}</div>
  <section className={styles.hero}><div className={styles.avatar}>{profile.photoURL?<img src={profile.photoURL} alt=""/>:profile.displayName?.[0]?.toUpperCase()||'S'}</div><div className={styles.identity}><h1>{profile.displayName}<span>✦</span></h1><p className={styles.handle}>@{profile.username}</p><p className={styles.bio}>{profile.bio||'No bio yet.'}</p><div className={styles.stats}><button onClick={()=>setActive('Followers')}><b>{profile.followersCount||0}</b> followers</button><button onClick={()=>setActive('Following')}><b>{profile.followingCount||0}</b> following</button><span><b>{collections.length}</b> collections</span><span><b>{reads.length}</b> recent reads</span></div></div></section>
  <nav className={styles.menu}>{tabs.map(tab=><button key={tab} onClick={()=>setActive(tab)} className={active===tab?styles.active:''}>{tab}</button>)}</nav>
  {message&&<div className={styles.message}>{message}</div>}
  {active==='Wall'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>PUBLIC WALL</p><h2>Wall</h2><span>Leave a little note for @{profile.username}.</span></div><MessageCircle size={20}/></div><div className={styles.rule}>✦ Please keep your notes kind and study-friendly.</div>{viewerUid&&<form className={styles.composer} onSubmit={postWall}><div className={styles.smallAvatar}>{profile.photoURL?<img src={profile.photoURL} alt=""/>:'S'}</div><textarea value={wallText} onChange={e=>setWallText(e.target.value)} placeholder={`Write something on @${profile.username}'s wall…`} maxLength={500}/><button disabled={busy||!wallText.trim()}><Send size={15}/></button></form>}<div className={styles.count}>{wall.length} {wall.length===1?'note':'notes'}</div>{wall.length===0?<div className={styles.empty}><div>♡</div><h3>No notes yet.</h3><p>Be the first person to leave something nice.</p></div>:<div className={styles.wallList}>{wall.map(post=><article className={styles.note} key={post.id}><div className={styles.smallAvatar}>{post.authorPhotoURL?<img src={post.authorPhotoURL} alt=""/>:post.authorDisplayName?.[0]?.toUpperCase()||'S'}</div><div className={styles.noteBody}><div className={styles.noteMeta}><b>{post.authorDisplayName}</b><span>@{post.authorUsername}</span><time>{dateLabel(post.createdAt)}</time></div><p>{post.text}</p></div></article>)}</div>}</section>}
  {active==='Collections'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>SUBJECT COLLECTIONS</p><h2>Collections</h2><span>Study spaces curated around what {profile.displayName} loves.</span></div><BookOpen size={20}/></div>{viewerUid===uid&&<button className={styles.create} onClick={()=>setShowCreate(v=>!v)}><Plus size={15}/> New collection</button>}{showCreate&&viewerUid===uid&&<form className={styles.createForm} onSubmit={createCollection}><input placeholder="Collection name" value={newCollection.title} onChange={e=>setNewCollection({...newCollection,title:e.target.value})}/><input placeholder="Subject" value={newCollection.subject} onChange={e=>setNewCollection({...newCollection,subject:e.target.value})}/><input placeholder="Short description (optional)" value={newCollection.description} onChange={e=>setNewCollection({...newCollection,description:e.target.value})}/><label><input type="checkbox" checked={newCollection.isPublic} onChange={e=>setNewCollection({...newCollection,isPublic:e.target.checked})}/><span>{newCollection.isPublic?<><Globe2 size={14}/> Public</>:<><Lock size={14}/> Private</>}</span></label><button disabled={busy}>Create collection ✦</button></form>}{collections.length===0?<div className={styles.empty}><div>◌</div><h3>{emptyCopy.Collections[0]}</h3><p>{emptyCopy.Collections[1]}</p></div>:<div className={styles.grid}>{collections.map(c=><article className={styles.collection} key={c.id}><div className={styles.collectionIcon}>✦</div><div><div className={styles.collectionTop}><span>{c.isPublic?<Globe2 size={13}/>:<Lock size={13}/>} {c.isPublic?'PUBLIC':'PRIVATE'}</span></div><h3>{c.title}</h3><b>{c.subject}</b><p>{c.description||'A little study universe.'}</p></div></article>)}</div>}</section>}
  {active==='Recent reads'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>RECENT ACTIVITY</p><h2>Recent reads</h2><span>The subjects and study material read most recently.</span></div><BookOpen size={20}/></div>{reads.length===0?<div className={styles.empty}><div>⌁</div><h3>{emptyCopy['Recent reads'][0]}</h3><p>{emptyCopy['Recent reads'][1]}</p></div>:<div className={styles.readList}>{reads.map(r=><article className={styles.read} key={r.id}><div className={styles.readIcon}><BookOpen size={17}/></div><div><b>{r.title}</b><span>{r.subject}</span></div><time>{dateLabel(r.readAt)}</time></article>)}</div>}</section>}
  {active==='Comments'&&<section className={styles.panel}><div className={styles.panelHead}><div><p>COMMENTS MADE</p><h2>Comments</h2><span>Notes {profile.displayName} has left on other people's study spaces.</span></div><MessageCircle size={20}/></div>{comments.length===0?<div className={styles.empty}><div>♡</div><h3>{emptyCopy.Comments[0]}</h3><p>{emptyCopy.Comments[1]}</p></div>:<div className={styles.commentList}>{comments.map(c=><article className={styles.comment} key={c.id}><MessageCircle size={16}/><div><p>{c.text}</p><span>on {c.noteTitle||'a study note'} · {dateLabel(c.createdAt)}</span></div></article>)}</div>}</section>}
  {(active==='Followers'||active==='Following')&&<section className={styles.panel}><div className={styles.panelHead}><div><p>PEOPLE</p><h2>{active}</h2><span>{active==='Followers'?`People following @${profile.username}.`:`People @${profile.username} follows.`}</span></div><Users size={20}/></div>{people.length===0?<div className={styles.empty}><div>◌</div><h3>{emptyCopy[active][0]}</h3><p>{emptyCopy[active][1]}</p></div>:<div className={styles.people}>{people.map(p=><a href={`/u/${p.username}`} className={styles.person} key={p.uid}><div className={styles.smallAvatar}>{p.photoURL?<img src={p.photoURL} alt=""/>:p.displayName?.[0]?.toUpperCase()||'S'}</div><div><b>{p.displayName}</b><span>@{p.username}</span></div><span className={styles.view}>View ↗</span></a>)}</div>}</section>}
  {active==='Stats'&&<section className={styles.statsPage}><div className={styles.statHeader}><div><p>READING ACTIVITY</p><h2>Stats</h2></div><BarChart3 size={20}/></div><div className={styles.statCards}>{[['TODAY',totals.today,'chapters'],['THIS WEEK',totals.week,'chapters · 7d'],['THIS MONTH',totals.month,'chapters · 30d'],['ALL-TIME',totals.all,'chapters'],['CURRENT STREAK',totals.streak,'days']].map(([a,b,c])=><div className={styles.statCard} key={String(a)}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className={styles.statsGrid}><div className={styles.chartCard}><p>LAST 30 DAYS</p><strong>{totals.month}</strong><span> chapters in the last 30 days</span><div className={styles.chart}>{Array.from({length:30},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(29-i));const v=activity.find(a=>{const ad=a.date?.toDate?a.date.toDate():new Date(a.date);return ad.toDateString()===d.toDateString()})?.chapters||0;return <i key={i} style={{height:`${Math.max(4,Math.min(100,v*4+4))}%`}} title={`${d.toLocaleDateString()}: ${v} chapters`}/>})}</div><div className={styles.axis}><span>30d ago</span><span>today</span></div></div><div className={styles.chartCard}><p>LAST 12 MONTHS</p><div className={styles.heatmap}>{Array.from({length:364},(_,i)=>{const v=activity.filter(a=>{const d=a.date?.toDate?a.date.toDate():new Date(a.date);return Math.floor((Date.now()-d.getTime())/86400000)===363-i}).reduce((s,a)=>s+(Number(a.chapters)||0),0);return <i key={i} className={v>20?styles.hot4:v>10?styles.hot3:v>4?styles.hot2:v>0?styles.hot1:''} title={`${v} chapters`}/>})}</div><div className={styles.legend}>Less <i/><i className={styles.hot1}/><i className={styles.hot2}/><i className={styles.hot3}/><i className={styles.hot4}/> More</div></div><div className={styles.chartCard}><p>TOP SUBJECTS</p>{(reads.length?Array.from(new Set(reads.map(r=>r.subject))).slice(0,5):['Programming','Mathematics','Data Structures','Electronics','Communication']).map((s,i)=><div className={styles.barRow} key={s}><span>{s}</span><i><em style={{width:`${100-i*16}%`}}/></i><b>{Math.max(0,100-i*17)}%</b></div>)}</div><div className={styles.chartCard}><p>STUDY LIBRARY</p><div className={styles.library}><div className={styles.donut}><span>{collections.length}</span><small>collections</small></div><div className={styles.libraryLegend}><span><i/>Public <b>{collections.filter(c=>c.isPublic).length}</b></span><span><i/>Private <b>{collections.filter(c=>!c.isPublic).length}</b></span><span><i/>Recent reads <b>{reads.length}</b></span></div></div></div></div></section>}
  <footer className={styles.footer}>STUKO · study, but make it yours.</footer>
 </div></main>;
}
