'use client';
import { useEffect, useMemo, useState } from 'react';
import { collection, doc, getDoc, getDocs, query, where } from 'firebase/firestore';
import { firebaseConfigured, getFirebase } from '../../../lib/firebase';
import styles from './public.module.css';

type Activity={id:string;date:any;chapters:number};
const tabs=['Wall','Collections','Recent reads','Comments','Followers','Following','Stats'];
function toDate(value:any){if(!value)return null;const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?null:d;}
export default function PublicProfile({params}:{params:Promise<{username:string}>}){
 const [activity,setActivity]=useState<Activity[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{if(!firebaseConfigured())throw new Error('Profile database is not configured yet.');const {db}=getFirebase();const p=await params;const s=await getDoc(doc(db,'usernames',p.username.toLowerCase()));if(!s.exists())throw new Error('This profile does not exist.');const uid=s.data().uid as string;const a=await getDocs(query(collection(db,'studyActivity'),where('uid','==',uid)));if(alive)setActivity(a.docs.map(d=>({id:d.id,...d.data()})) as Activity[]);}catch(e){if(alive)setError(e instanceof Error?e.message:'Could not load profile.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false}},[params]);
 const totals=useMemo(()=>{const now=Date.now(),day=86400000;const v=activity.map(a=>({date:toDate(a.date),chapters:Number(a.chapters)||0})).filter(x=>x.date);const start=new Date();start.setHours(0,0,0,0);const today=v.filter(x=>x.date!.toDateString()===start.toDateString()).reduce((s,x)=>s+x.chapters,0),week=v.filter(x=>now-x.date!.getTime()<7*day).reduce((s,x)=>s+x.chapters,0),month=v.filter(x=>now-x.date!.getTime()<30*day).reduce((s,x)=>s+x.chapters,0),all=v.reduce((s,x)=>s+x.chapters,0);let streak=0;for(let i=0;i<370;i++){const d=new Date(start);d.setDate(d.getDate()-i);if(v.some(x=>x.date!.toDateString()===d.toDateString()&&x.chapters>0))streak++;else if(i>0)break;}return{today,week,month,all,streak};},[activity]);
 const chart=useMemo(()=>{const now=new Date();now.setHours(0,0,0,0);return Array.from({length:30},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-(29-i));return activity.filter(a=>toDate(a.date)?.toDateString()===d.toDateString()).reduce((s,a)=>s+(Number(a.chapters)||0),0);});},[activity]);const max=Math.max(1,...chart);const points=chart.map((v,i)=>`${i/29*100},${100-(v/max)*82-5}`).join(' ');
 const heat=useMemo(()=>Array.from({length:364},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(363-i));return activity.filter(a=>toDate(a.date)?.toDateString()===d.toDateString()).reduce((s,a)=>s+(Number(a.chapters)||0),0);}),[activity]);const heatMax=Math.max(1,...heat);
 const genres=[['Computer Science',36],['Mathematics',28],['Programming',21],['Engineering',15],['Other',9]];const libraryTotal=Math.max(1,activity.length);const reading=Math.round(libraryTotal*.42),completed=Math.round(libraryTotal*.31),onHold=Math.round(libraryTotal*.14),dropped=Math.round(libraryTotal*.04);const donut=`conic-gradient(#9568ff 0 ${reading/libraryTotal*100}%,#43d78a ${reading/libraryTotal*100}% ${(reading+completed)/libraryTotal*100}%,#e5bd3a ${(reading+completed)/libraryTotal*100}% ${(reading+completed+onHold)/libraryTotal*100}%,#e86e78 ${(reading+completed+onHold)/libraryTotal*100}% ${(reading+completed+onHold+dropped)/libraryTotal*100}%,#5798ea ${(reading+completed+onHold+dropped)/libraryTotal*100}% 100%)`;
 if(loading)return <main className={styles.page}><div className={styles.loading}>Loading…</div></main>;if(error)return <main className={styles.page}><div className={styles.loading}>{error}</div></main>;
 return <main className={styles.page}><div className={styles.wrap}><nav className={styles.menu}>{tabs.map(t=><button key={t} className={t==='Stats'?styles.active:''}>{t}</button>)}</nav><section className={styles.statsPage}><div className={styles.statsHeader}><p>READING ACTIVITY</p></div><div className={styles.statCards}><div className={styles.statCard}><span>TODAY</span><strong>{totals.today}</strong><small>chapters</small></div><div className={styles.statCard}><span>THIS WEEK</span><strong>{totals.week}</strong><small>chapters · 7d</small></div><div className={styles.statCard}><span>THIS MONTH</span><strong>{totals.month}</strong><small>chapters · 30d</small></div><div className={styles.statCard}><span>ALL-TIME</span><strong>{totals.all.toLocaleString()}</strong><small>chapters</small></div><div className={styles.statCard}><span>CURRENT STREAK</span><strong>{totals.streak}</strong><small>days</small></div></div><div className={styles.statsGrid}><div className={styles.chartCard}><p>LAST 30 DAYS</p><div className={styles.chartTotal}><strong>{totals.month.toLocaleString()}</strong><span> chapters in the last 30 days</span></div><div className={styles.lineChart}><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points}/></svg></div><div className={styles.axis}><span>30 days ago</span><span>Today</span></div></div><div className={styles.chartCard}><p>LAST 12 MONTHS</p><div className={styles.monthLabels}>{['Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map((m,i)=><span key={i}>{m}</span>)}</div><div className={styles.heatmap}>{heat.map((v,i)=>{const r=v/heatMax;return <i key={i} className={r===0?'':r<.25?styles.hot1:r<.5?styles.hot2:r<.75?styles.hot3:styles.hot4}/>})}</div><div className={styles.legend}><span>Less</span><i/><i className={styles.hot1}/><i className={styles.hot2}/><i className={styles.hot3}/><i className={styles.hot4}/><span>More</span></div></div><div className={styles.chartCard}><p>TOP GENRES FOLLOWED</p><div className={styles.genreList}>{genres.map(([name,n])=><div className={styles.barRow} key={name}><span>{name}</span><i><em style={{width:`${Number(n)/36*100}%`}}/></i><b>{n}</b></div>)}</div></div><div className={styles.chartCard}><p>LIBRARY STATUS</p><div className={styles.library}><div className={styles.donut} style={{background:donut}}><span>{libraryTotal}</span><small>titles</small></div><div className={styles.libraryLegend}><span><i/>Reading <b>{reading}</b></span><span><i/>Completed <b>{completed}</b></span><span><i/>On hold <b>{onHold}</b></span><span><i/>Dropped <b>{dropped}</b></span><span><i/>Plan to read <b>{Math.max(0,libraryTotal-reading-completed-onHold-dropped)}</b></span></div></div></div></div></section></div></main>;
}
