'use client';
import { useEffect, useRef, useState } from 'react';
import SiteChrome from '@/app/components/SiteChrome';
export default function DocumentReaderPage(){
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[text,setText]=useState('');const editor=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 const openFile=(f:File)=>{if(url)URL.revokeObjectURL(url);setFile(f);setUrl(URL.createObjectURL(f));if(f.type.startsWith('text/')||f.name.endsWith('.txt')){const r=new FileReader();r.onload=()=>setText(String(r.result||''));r.readAsText(f)}else setText('')};
 const speak=()=>{if(typeof window==='undefined')return;window.speechSynthesis.cancel();const source=text||editor.current?.innerText||'';if(source)window.speechSynthesis.speak(new SpeechSynthesisUtterance(source))};
 const format=(cmd:string,val?:string)=>{editor.current?.focus();document.execCommand(cmd,false,val)};
 return <SiteChrome><main className="reader-page"><section className="reader-card"><p className="kicker">study reader</p><h1>upload & annotate</h1><p className="sub">bring your PDFs, Word documents, or PowerPoints into your study space.</p><label className="drop"><input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.txt" onChange={e=>e.target.files?.[0]&&openFile(e.target.files[0])}/><strong>choose a file</strong><span>PDF · DOC · DOCX · PPT · PPTX · TXT</span></label>{file&&<div className="file-name">{file.name}</div>}<div className="toolbar"><button onClick={()=>format('bold')}>bold</button><button onClick={()=>format('underline')}>underline</button><button onClick={()=>format('hiliteColor','#fff29a')}>highlight</button><button onClick={speak}>text to speech</button><button className="ghost" onClick={()=>window.speechSynthesis?.cancel()}>stop</button></div><div ref={editor} className="editor" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{__html:text?text.replace(/\n/g,'<br/>'):''}}></div>{file?.type==='application/pdf'&&<iframe className="preview" src={url} title="PDF preview"/>}{file&&file.type!=='application/pdf'&&<p className="hint">The file is loaded locally. Browser-native preview is available for PDFs; for Word/PowerPoint files, use the annotation area above after copying the text you want to study.</p>}</section></main><style jsx>{`.reader-page{min-height:calc(100svh - 150px);padding:150px 20px 100px;display:grid;place-items:center}.reader-card{width:min(1000px,100%);padding:42px;border:1px solid var(--glass-border);border-radius:30px;background:var(--glass-bg);backdrop-filter:blur(12px);color:var(--page-text)}.kicker{font:12px monospace;letter-spacing:.15em;text-transform:uppercase}.reader-card h1{font-size:clamp(48px,7vw,80px);font-weight:400;letter-spacing:-.07em;margin:10px 0}.sub{opacity:.65}.drop{margin-top:28px;border:1px dashed var(--glass-border);border-radius:22px;min-height:130px;display:grid;place-items:center;text-align:center;cursor:pointer;padding:20px}.drop input{display:none}.drop strong{font-size:18px}.drop span{font-size:12px;opacity:.5}.file-name{margin-top:12px;opacity:.65;font-size:13px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.toolbar button{border:1px solid var(--glass-border);border-radius:999px;padding:9px 14px;background:transparent;color:inherit;cursor:pointer}.toolbar button:hover{background:rgba(255,255,255,.12)}.toolbar .ghost{opacity:.7}.editor{min-height:360px;border:1px solid var(--glass-border);border-radius:18px;padding:20px;line-height:1.75;outline:none;background:rgba(255,255,255,.03)}.editor:empty:before{content:'paste or type readable text here to annotate…';opacity:.35}.preview{width:100%;height:560px;border:1px solid var(--glass-border);border-radius:18px;margin-top:16px}.hint{font-size:13px;opacity:.55;margin-top:14px}`}</style></SiteChrome>
}